@echo off
REM Start DesignBridge (FastAPI backend + Vue frontend)
echo Starting DesignBridge API...
start cmd /k "python -m uvicorn api:app --reload --host 0.0.0.0 --port 8000"
echo Starting DesignBridge Frontend...
start cmd /k "cd frontend && npm run dev"
